language: node_js
node_js:
  - "4.0"
addons:
  firefox: "45.0"
  apt:
    packages:
      - xvfb
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp"
  - "export PATH="/tmp/firefox:$PATH"
  - "echo "Using firefox version `firefox --version`"
install:
  - npm install
script:
  - npm test
notifications:
  email: false
