language: node_js
node_js:
  - "4.0"
addons:
  apt:
    packages:
      - xvfb
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - npm install
script:
  - npm test
notifications:
  email: false
