language: node_js
node_js:
  - "4.0"
env:
  global:
    - NODE_ENV=travis
addons:
  apt:
    packages:
      - xvfb
  firefox: "45.0"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - tar -xjf /tmp/firefox-45.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"
install:
  - npm install
script:
  - npm run test:travis
after_success:
  - npm run codecov
notifications:
  slack: devlucky:ZlrFWfC8hwIF2U4HXDAKqdwr
  email: false
